manifest:
    file_name: ./data/imaging_data_manifest_2021_09_23.tsv
    package_attribute: series_uid

aws:
    access_key: test
    secret_key: test
    bucket: test

n3c:
    file_name: ./data/N3C-TransitTokens_ACR_TestBatch_SUBMISSION_20200705.csv
    query_attribute: 'ACR CASE ID'
    commons: data.midrc.org
